language: node_js
node_js:
 - "stable"
services: psql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
install:
 - yarn
 - yarn buildEnv
 - yarn setup:server
 - yarn setup:client
script:
 - yarn build
 - yarn start:server

